import { Component } from '@angular/core';

@Component({
  selector: 'app-first-component',
  standalone: true,
  imports: [],
  templateUrl: './first-component.component.html',
  styleUrl: './first-component.component.css',
})
export class FirstComponentComponent {
  title = 'First component';
  text = 'This is some dummy text to test paragraph tag';
  desc =
    'Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere doloremque aut esse quidem vero nisi, impedit quia ad quisquam excepturi inventore est exercitationem et totam suscipit consectetur, tenetur rerum dolorem aperiam sunt sed, atque voluptates? Laboriosam corporis quia adipisci ipsa repellat possimus tempore ex praesentium accusantium eaque voluptate aliquid, quo nulla vitae quasi hic cupiditate laudantium similique quisquam? Unde hic aliquam tempora beatae repudiandae distinctio quasi enim, sit velit, dolores nobis reprehenderit inventore dignissimos delectus. Ratione porro ad accusamus, soluta unde vel quia. Error dolore distinctio neque quos, hic totam cumque fugiat sunt possimus omnis impedit illum in fuga accusantium tempora, aliquam autem magni fugit? Nemo sunt ipsam delectus, voluptate, cum velit, numquam aut voluptas dolores eos fugiat voluptatibus. Possimus explicabo a minima maxime quasi dolor, magnam omnis fugiat fuga culpa optio cumque quibusdam eos animi harum delectus earum deserunt sequi obcaecati temporibus deleniti? Molestias in necessitatibus temporibus officiis perferendis. Dolorem autem distinctio reprehenderit incidunt, iusto, molestiae eaque placeat officiis reiciendis assumenda ea soluta, enim similique vero voluptatibus quisquam? Illum delectus labore tempora quisquam totam, sunt dicta similique possimus id, odio, veritatis perspiciatis. Vitae maxime error id velit, adipisci minima aspernatur nobis voluptatem atque! Voluptas, delectus quasi blanditiis modi, harum, voluptatibus earum accusantium dignissimos reiciendis animi est necessitatibus iusto maiores culpa ullam suscipit exercitationem rerum dolores molestias deleniti id vel eligendi reprehenderit! Numquam placeat animi amet? Unde necessitatibus libero debitis at, aperiam nam animi, autem in hic, aliquid iure! In laboriosam quo vel excepturi corporis maiores tempora architecto inventore, dolorem molestias distinctio sapiente animi saepe porro autem est! Voluptates sequi voluptas recusandae magnam. Recusandae laboriosam, voluptatem, tempore labore ab accusamus ut dolorum odit vitae omnis harum cumque natus iste hic et rem, reiciendis corrupti sapiente pariatur magni dolore quia! Nostrum cupiditate aspernatur saepe repellendus, assumenda magnam doloremque ipsam provident omnis!';
  card1title="Card 1";
  card1desc="Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere doloremque aut esse quidem vero nisi, impedit quia ad quisquam excepturi inventore est exercitationem et totam suscipit consectetur, tenetur rerum dolorem aperiam sunt sed, atque voluptates? Laboriosam corporis quia adipisci ipsa repellat possimus tempore ex praesentium accusantium eaque voluptate aliquid, quo nulla vitae quasi hic cupiditate laudantium similique quisquam?";
  card2title="Card 2";
  card2desc="Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere doloremque aut esse quidem vero nisi, impedit quia ad quisquam excepturi inventore est exercitationem et totam suscipit consectetur, tenetur rerum dolorem aperiam sunt sed, atque voluptates? Laboriosam corporis quia adipisci ipsa repellat possimus tempore ex praesentium accusantium eaque voluptate aliquid, quo nulla vitae quasi hic cupiditate laudantium similique quisquam?";
  card3title="Card 3";
  card3desc="Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere doloremque aut esse quidem vero nisi, impedit quia ad quisquam excepturi inventore est exercitationem et totam suscipit consectetur, tenetur rerum dolorem aperiam sunt sed, atque voluptates? Laboriosam corporis quia adipisci ipsa repellat possimus tempore ex praesentium accusantium eaque voluptate aliquid, quo nulla vitae quasi hic cupiditate laudantium similique quisquam?";
  card4title="Card 4";
  card4desc="Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere doloremque aut esse quidem vero nisi, impedit quia ad quisquam excepturi inventore est exercitationem et totam suscipit consectetur, tenetur rerum dolorem aperiam sunt sed, atque voluptates? Laboriosam corporis quia adipisci ipsa repellat possimus tempore ex praesentium accusantium eaque voluptate aliquid, quo nulla vitae quasi hic cupiditate laudantium similique quisquam?";
  card5title="Card 5";
  card5desc="Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere doloremque aut esse quidem vero nisi, impedit quia ad quisquam excepturi inventore est exercitationem et totam suscipit consectetur, tenetur rerum dolorem aperiam sunt sed, atque voluptates? Laboriosam corporis quia adipisci ipsa repellat possimus tempore ex praesentium accusantium eaque voluptate aliquid, quo nulla vitae quasi hic cupiditate laudantium similique quisquam?";
}
